restart_hook = "systemctl restart minecraft"

servers = {
    "velocity": {
        "server": "velocity",
        "plugins": ["geyser", "floodgate"],
        "restart_hook": "systemctl restart velocity",
    },
    "searanch": {
        "server": "paper",
        "plugins": ["squaremap", "discordsrv", "simple-voice-chat"],
        "restart_hook": "systemctl restart searanch",
    },
    "benworld": {
        "server": "paper",
        "plugins": ["squaremap"],
        "restart_hook": "systemctl restart benworld",
    },
}
